"""Change photo column data type

Revision ID: 6c5b75eec792
Revises: 7a7878422394
Create Date: 2024-04-04 01:45:21.298545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5b75eec792'
down_revision = '7a7878422394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.BLOB(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.String(length=200),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
