"""Initial migration

Revision ID: 7a7878422394
Revises: baaf60d70f73
Create Date: 2024-04-02 12:34:41.479551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a7878422394'
down_revision = 'baaf60d70f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voting_status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('voted_for', sa.Integer(), nullable=True))
        batch_op.drop_column('votingStatus')
        batch_op.drop_column('votedFor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votedFor', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('votingStatus', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('voted_for')
        batch_op.drop_column('voting_status')

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
