"""add email in eligible users

Revision ID: 806872e4d71f
Revises: 6c5b75eec792
Create Date: 2024-04-15 19:45:26.346622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806872e4d71f'
down_revision = '6c5b75eec792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eligible_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eligible_users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
