"""adding columns i users db

Revision ID: 9f058b1e7b56
Revises: 
Create Date: 2024-03-30 22:11:20.325893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f058b1e7b56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votingStatus', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('votedFor', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('votedFor')
        batch_op.drop_column('votingStatus')

    # ### end Alembic commands ###
